import type { GenerationResult } from './analyzer.js';

// ============================================================================
// Output Formatters
// ============================================================================

/**
 * Format generation results as a single Markdown document.
 */
export function formatAsMarkdown(results: GenerationResult[]): string {
  return results.map((r) => r.content).join('\n---\n\n');
}

/**
 * Format generation results as a PR comment body.
 */
export function formatAsPRBody(results: GenerationResult[]): string {
  const lines: string[] = [
    '## 📝 DocSynth Documentation Update',
    '',
    '> Automatically generated documentation suggestions based on code changes.',
    '',
  ];

  for (const result of results) {
    lines.push(`### ${formatDocType(result.type)}`, '');
    lines.push(`📄 **Target file**: \`${result.path}\``, '');
    lines.push('<details>', `<summary>View suggested content</summary>`, '');
    lines.push(result.content);
    lines.push('</details>', '');
  }

  lines.push(
    '---',
    '*Generated by [DocSynth](https://github.com/docsynth) — AI-powered documentation*'
  );

  return lines.join('\n');
}

/**
 * Format generation results as a JSON string.
 */
export function formatAsJSON(results: GenerationResult[]): string {
  return JSON.stringify(
    {
      generated: results.map((r) => ({
        type: r.type,
        path: r.path,
        content: r.content,
        metadata: r.metadata,
      })),
      generatedAt: new Date().toISOString(),
      count: results.length,
    },
    null,
    2
  );
}

// ============================================================================
// Internal Helpers
// ============================================================================

function formatDocType(type: string): string {
  const labels: Record<string, string> = {
    readme: '📖 README',
    changelog: '📋 Changelog',
    'api-reference': '🔧 API Reference',
    'migration-guide': '🔄 Migration Guide',
  };
  return labels[type] ?? type;
}
